name: "Lesson 2 - Exercise 3"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent reruns
        run: |
          # Exit if the run number is greater than the maximum number of attempts
          if [ $RUN_ATTEMPT_NUMBER -gt $MAXIMUM_ATTEMPTS ]; then
            echo "Exiting because the run number is greater than the maximum number of attempts"
            exit 1
          fi
        env: 
          MAXIMUM_ATTEMPTS: ${{ vars.Max_Attempts }}
          RUN_ATTEMPT_NUMBER: ${{ github.run_attempt }}
          
      - name: Run job
        run: |
          echo "Running job"
          sleep 1
